version: '3'

services:
  php:
    container_name: "php"
    build: ./docker/php
    volumes:
      - .:/app

  nginx:
    image: nginx
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql
    container_name: "db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
